services:
  postgres:
    image: 'postgres:18.3-alpine'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=open-crm'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    networks:
      - app-network

  mailhog:
      image: mailhog/mailhog:v1.0.1
      restart: unless-stopped
      networks:
        - app-network
      ports:
        - '1025:1025'
        - '8025:8025'

networks:
  app-network:
    driver: bridge