package com.open.crm.core.entities.employee;

public enum AccessPermission {
  EMPLOYEE_READ,
  EMPLOYEE_UPDATE,
  EMPLOYEE_ACCESS,

  CLIENT_READ,
  CLIENT_UPDATE,
  CLIENT_NAME_SHOW,
  CLIENT_CONTACT_SHOW,

  INVESTIGATION_LOG_READ,

  COMMODITY_READ,
  COMMODITY_UPDATE,
}
