version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    dns:
      - 8.8.8.8
      - 1.1.1.1

  db:
    image: postgres:18.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: crm
    # Spring Boot should connect to the database via jdbc:postgresql://db:5432/crm
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

  thooks:
    image: gitverse.ru/batiukhnonikita/thook:v0.1.0
    restart: unless-stopped
  ports:
      - "8825:3000"   

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8888:80"
