services:
  dev:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      "args": { "USERNAME": "devuser" }
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/devuser/.ssh:ro
      - ~/.gitconfig:/home/devuser/.gitconfig:ro
      - bash_history:/commandhistory
      - ${SSH_AUTH_SOCK}:/run/ssh-agent.sock
    environment:
      - SSH_AUTH_SOCK=/run/ssh-agent.sock
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=devuser
      - PGPASSWORD=devpassword
      - PGDATABASE=crm
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - REACT_APP_BACKEND_URL=localhost:8080
      - JWT_SECRET=rZaL5vR7SaHsH0DryywXyoh44QJlX9PQEKTKK4nShQtfxbjGR5yIrIEJMAj2awCb
    depends_on:
      - database
      - mailhog
    networks:
      dev-network:
        aliases:
          - app
          - backend
          - frontend

  database:
    image: postgres:18.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: crm
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      dev-network:
        aliases:
          - database
          - postgres

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      dev-network:
        aliases:
          - mailhog

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - dev-network

volumes:
  pgadmin_data:
  postgres_data:
  bash_history:

networks:
  dev-network:
    driver: bridge
